source 'https://rubygems.org'
group :jekyll_plugins do
  gem 'github-pages'
  gem 'jekyll-paginate'
  gem 'jekyll-sitemap'
  gem 'jekyll-gist'
  gem 'jekyll-feed'
  gem 'jemoji'
  gem 'jekyll-include-cache'
  gem 'jekyll-algolia'
end
gem 'minimal-mistakes-jekyll'